const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const geometry = vm.createContext({});
vm.runInContext(fs.readFileSync(path.join(__dirname, '../SaberGeometry.js'), 'utf8'), geometry);
const prev = {base: {x: 0, y: 0}, tip: {x: 100, y: 0}};
const next = {base: {x: 0, y: 100}, tip: {x: 100, y: 100}};
assert(geometry.hits(50, 50, 5, prev, next), 'fast sweep catches interior');
assert(geometry.hits(104, 50, 5, prev, next), 'blade edge has a radius');
assert(!geometry.hits(110, 50, 5, prev, next), 'outside sweep misses');
assert(!geometry.hits(10000, 10000, 5, prev, prev), 'degenerate sweep does not hit the entire screen');
assert(geometry.hits(50, 3, 5, prev, prev), 'stationary blade contact');
assert(!geometry.hits(-20, 0, 5, prev, prev), 'behind hilt misses');
const rotated = {base: {x: 0, y: 0}, tip: {x: 0, y: 100}};
assert(geometry.hits(25, 25, 5, prev, rotated), 'rotating blade catches arc interior');
assert(!geometry.hits(-25, -25, 5, prev, rotated), 'opposite quadrant misses');
const blade = geometry.blade(100, 200, 90, 2.0);
assert(Math.abs(blade.base.x - 100) < 1e-8);
assert(Math.abs(blade.tip.y - 360) < 1e-8, 'geometry matches art tip');
const rules = vm.createContext({});
vm.runInContext(fs.readFileSync(path.join(__dirname, '../FlyRound.js'), 'utf8'), rules);
const round = rules.fresh(0, 'lightsaber');
for (let i = 0; i < 4; i++) rules.kill(round, 2);
const record = rules.finish(round, rules.roundSeconds * 1000);
assert.equal(record.score, 1000);
assert.equal(rules.restore(JSON.stringify({version: 1, records: [record]}))[0].weapon, 'lightsaber');
console.log('Saber swept collision, misses, art alignment, multi-kill scoring, and records passed.');
